name: One Workflow

on: 
  workflow_dispatch  # Enables manual triggering of the workflow

jobs:
  first-job:
    runs-on: ubuntu-latest  # ✅ Corrected from 'run-on' to 'runs-on'
    
    steps:
      - name: Print greeting
        run: |
            echo "Hi"
            echo "Hello World"

      - name: Print goodbye
        run: echo "Bye See You soon"
